#!/usr/bin/env bash
#
##############################################################################
# Copyright 20015 rcrowther
#
# This is free software; see the distribution for copying conditions.
# There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
##############################################################################

## Point at a scala installation
# If empty tries for an installed version.
#SCALA_HOME=""

if [[ -n "$SCALA_HOME" ]]; then
SCALAEXE="$SCALA_HOME/bin/scaladoc" 
else
SCALAEXE="scaladoc"
fi

echo "creating documentation..."

mkdir doc

SRCS="$(find $PWD/src/main | grep scala$)"
#echo ${SRCS}

$SCALAEXE -toolcp lib/script_0.2.1.jar -d doc -doc-title SSC -doc-footer "by rcrowther" -doc-root-content src/main/rootdoc.txt $SRCS
